language: go
go:
        - stable
script:
        - go get -t ./...
        - go test ./...
        - go vet .
        - go vet ./lib
        - diff -u <(echo -n) <(gofmt -d -s .)
        - diff -u <(echo -n) <(gofmt -d -s ./lib)
after_success:
        - ./scripts/coverage.sh
